[package]
name = "tftp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fsm"
path = "src/fsm/ideias-async.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
async-std = "1.12"